development:
  adapter: postgresql
  encoding: unicode
  database: harvest-status-development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: harvest-status-test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: harvest-status-production
  pool: 5
  host: localhost
  username: deploy
  password:
